routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});

//Auth::routes();

/*
|--------------------------------------------------------------------------
| Logging In/Out Routes
|--------------------------------------------------------------------------
*/
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::get('logout', 'Auth\LoginController@logout');

Route::group([ 'middleware' => 'auth' ], function () {
    Route::get('/', 'HomeController@index')->name('home');

    /*
     |--------------------------------------------------------------------------
     | Admin User CRUD Routes
     |--------------------------------------------------------------------------
     */
    Route::group([ 'as' => 'user.', 'prefix' => 'user' ], function () {
        Route::get('', 'UserController@index')->name('index');
        Route::get('create', 'UserController@create')->name('create');
        Route::post('', 'UserController@store')->name('store');
        Route::get('{user}/edit', 'UserController@edit')->name('edit');
        Route::put('{user}', 'UserController@update')->name('update');
        Route::delete('{user}', 'UserController@destroy')->name('destroy');
    });

    /*
     |--------------------------------------------------------------------------
     | Ticket Routes
     |--------------------------------------------------------------------------
     */
    Route::group([ 'as' => 'ticket.', 'prefix' => 'ticket' ], function () {
        Route::get('', 'TicketController@index')->name('index');
        Route::get('{ticket}/details', 'TicketController@show')->name('show');
//        Route::get('create', 'TicketController@create')->name('create');
//        Route::post('', 'TicketController@store')->name('store');
//        Route::get('{user}/edit', 'TicketController@edit')->name('edit');
        Route::put('comment/{ticket}', 'TicketController@comment')->name('comment');
//        Route::delete('{user}', 'TicketController@destroy')->name('destroy');
    });
});

resources/views/layouts/partials/errors.blade.php
@if( isset($errors) && ! empty($errors->all()))
    <div class="alert alert-callout alert-warning alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        <ul>
            <?php $dumpErrors = []; ?>
            @foreach( $errors->all() as $pos => $error )
                @if( !in_array($error, $dumpErrors) )
                    <li>{{ $error }}</li>
                    <?php $dumpErrors[] = $error; ?>
                @endif
            @endforeach
        </ul>
    </div>
@endif
@if(session('status'))
    <div class="alert alert-callout alert-warning alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        <p>{!! session('status') !!}</p>
    </div>
@endif

resources/views/layouts/partials/global-script.blade.php
<script>
//Session messages
var successMsg = "{{ session('success') }}";
var infoMsg = "{{ session('info') }}";
var warningMsg = "{{ session('warning') }}";
var dangerMsg = "{{ session('danger') }}";
var errorMsg;
@if(count($errors))
    <?php $allErrors = '<ul>'; ?>

    @foreach($errors->all() as $errors)
        <?php $allErrors .= '<li>'.$errors.'</li>'; ?>
    @endforeach
    <?php $allErrors .= '</ul>'; ?>

    var errorMsg = "{!! $allErrors !!}";
@endif

//Active links
var requestUrl = "{{ request()->url() }}";
</script>

resources/views/layouts/partials/header.blade.php
<header id="header" class="header-inverse">
    <div class="headerbar">
        <div class="headerbar-left">
            <ul class="header-nav header-nav-options">
                <li class="header-nav-brand">
                    <div class="brand-holder">
                        <a href="{{url('/')}}">
                            <span class="text-lg text-bold text-primary">{{ config('app.name', 'System') }}</span>
                        </a>
                    </div>
                </li>
                <li>
                    <a class="btn btn-icon-toggle menubar-toggle" data-toggle="menubar" href="javascript:void(0);">
                        <i class="md md-menu"></i>
                    </a>
                </li>
            </ul>
        </div>
        <div class="headerbar-right">
            <ul class="header-nav header-nav-options">
            </ul>
            <ul class="header-nav header-nav-profile">
                <li class="dropdown">
                    <a href="javascript:void(0);" class="dropdown-toggle ink-reaction" data-toggle="dropdown">
                        <img src="{{ user_avatar(50) }}" alt=""/>
                        <span class="profile-info">
                            {{ auth()->user()->name }}
{{--                            <small>{{ display(auth()->user()->roles->pluck('name')->implode(', '), 'None') }}</small>--}}
                        </span></a>
                    <ul class="dropdown-menu animation-dock">
                        <li class="dropdown-header">Config</li>
                        <li>
{{--                            <a href="{{ route('user.show', auth()->user()->username) }}">--}}
                            <a href="{{-- route('user.show') --}}">
                                <i class="md md-account-circle"></i>
                                My profile
                            </a>
                        </li>
                        <li>
                            <a href="{{-- route('setting.index') --}}">
                                <i class="md md-settings"></i>
                                Settings
                            </a>
                        </li>
                        <li>
                            <a href="{{ url('/logout') }}">
                                <i class="md md-settings-power text-danger"></i>
                                Logout
                            </a>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</header>

resources/views/layouts/partials/menubar.blade.php
<!-- BEGIN MENUBAR-->
<div id="menubar" class="animate">
    <div class="menubar-fixed-panel">
        <div>
            <a class="btn btn-icon-toggle btn-default menubar-toggle" data-toggle="menubar" href="javascript:void(0);">
                <i class="fa fa-bars"></i>
            </a>
        </div>
        <div class="expanded">
            <a href="{{ url('/') }}">
                <span class="text-lg text-bold text-primary text-uppercase">{{ config('app.name') }}</span>
            </a>
        </div>
    </div>
    <div class="menubar-scroll-panel">
        <!-- BEGIN MAIN MENU -->
        <ul id="main-menu" class="gui-controls">
            @foreach($allMenu as $menu)
                <li class="menu {{ $menu['class'] ?: '' }}">
                    <a href="{{ $menu['route'] }}">
                        @if(isset($menu['icon']))
                            <div class="gui-icon">
                                <i class="{{ $menu['icon'] }}"></i>
                            </div>
                        @else
                            <div class="gui-icon gui-text">
                                {{ $menu['text'] }}
                            </div>
                        @endif
                        <span class="title">{{ $menu['title'] }}</span>
                    </a>
                    @if(isset($menu['items']))
                        <ul>
                            @foreach($menu['items'] as $item)
                                @if(isset($item['items']))
                                    <li class="gui-folder">
                                        <a href="javascript:void(0);">
                                            <span class="title sub">{{ $item['title'] }}</span>
                                        </a>
                                        <ul>
                                            @foreach($item['items'] as $subItem)
                                                <li>
                                                    <a href="{{ $subItem['route'] }}">
                                                        <span class="title">{{ $subItem['title'] }}</span>
                                                    </a>
                                                </li>
                                            @endforeach
                                        </ul>
                                    </li>
                                @else
                                    <li class="sub-menu">
                                        <a href="{{ $item['route'] }}">
                                            <span class="title sub">{{ $item['title'] }}</span>
                                        </a>
                                    </li>
                                @endif
                            @endforeach
                        </ul>
                    @endif
                </li>
            @endforeach

        </ul><!--end .main-menu -->
        <!-- END MAIN MENU -->
        <div class="menubar-foot-panel">
            <small class="no-linebreak hidden-folded">
                <span class="opacity-75">Copyright &#183; {{ date('Y') }} &#183;</span>
                <strong>
                    <a href="{{ url('/') }}"> {{ config('app.name') }}</a>
                </strong>
            </small>
        </div>
    </div><!--end .menubar-scroll-panel-->
</div><!--end #menubar-->
<!-- END MENUBAR -->